# Generated by Django 4.2.1 on 2023-05-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSuc', models.CharField(max_length=80)),
                ('Encargado', models.CharField(max_length=80)),
                ('NumEmpleados', models.IntegerField()),
                ('Ubicacion', models.CharField(max_length=80)),
            ],
        ),
    ]
