# Generated by Django 4.2.1 on 2023-05-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=10)),
                ('Marca', models.CharField(max_length=40)),
                ('Modelo', models.CharField(max_length=50)),
                ('Año', models.IntegerField()),
                ('Conductor', models.CharField(max_length=80)),
            ],
        ),
    ]
