# Generated by Django 4.2.1 on 2023-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoDeCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Marca', models.CharField(max_length=45)),
                ('Potencia', models.IntegerField()),
                ('Antiguedad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=60)),
                ('Presentacion', models.CharField(max_length=45)),
                ('Precio', models.FloatField()),
                ('Sabor', models.CharField(max_length=55)),
            ],
        ),
    ]
