# Generated by Django 4.2.1 on 2023-05-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postre', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
