# Generated by Django 4.2.1 on 2023-05-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0002_remove_equipo_antiguedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sabor',
        ),
    ]
